//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilibiliReplyLottery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryReady
    {
        public int LotteryId { get; set; }
        public string AvNum { get; set; }
        public Nullable<int> LotteryNum { get; set; }
        public Nullable<System.DateTime> LotteryTime { get; set; }
        public Nullable<int> IsExecuted { get; set; }
        public Nullable<int> IsFilter { get; set; }
    }
}
