//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilibiliReplyLottery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LotteryAccount
    {
        public int LID { get; set; }
        [Required(ErrorMessage = "必须填写登录名")]
        [StringLength(20,MinimumLength =3,ErrorMessage ="登录名长度必须大于3小于20")]
        public string LotteryName { get; set; }
        [Required(ErrorMessage = "必须填写密码")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "密码长度必须大于6小于20")]
        public string LotteryPsw { get; set; }
        public Nullable<int> LotteryCount { get; set; }
    }
}
